pipeline {
    agent any
    tools {
        nodejs 'nodejs'
    }
    stages {
        stage('installing') {
            steps {
                sh 'npm install'
            }
        }
        
        stage('packing') {
            steps {
                sh 'npm pack'
            }
        
        }
        stage('starting') {
            steps {
                sh 'npm start'
            }
        }
       
    }
}
